In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
dframe=pd.read_csv('usedcars.csv')
print(dframe)

            Brand      Model  Year  Mileage_kmpl    Engine_CC  Horsepower  \
0          Toyota      Camry  2001     19.615852  1396.560379         NaN
1         Hyundai        i20  2012     19.478608  1130.771005  137.021719
2        Mahindra     Bolero  2008     17.469920  1766.466250  142.902960
3             BMW         X1  2015     21.295421          NaN   49.782079
4           Honda      Civic  2022     18.326833  1239.334935  121.505993
...           ...        ...   ...           ...          ...         ...
1004995    Nissan    Magnite  2022     12.256422  1773.657889  117.574596
1004996     Honda      Amaze  2005           NaN  1705.773023   99.643689
1004997     Skoda    Octavia  2018     21.665335  1447.159515         NaN
1004998       BMW         X3  2010     17.852635  2179.906631         NaN
1004999      Ford  Endeavour  2010     20.839002   800.000000   11.857082

        Fuel_Type Transmission Owner_Type  Color       City  Kms_Driven  \
0          Hybrid    Automatic      First   Grey    Chennai      500928
1          Petrol          NaN      First   Grey     Mumbai      211510
2             NaN    Automatic      First  Black    Kolkata      333999
3             NaN       Manual      First  White       Pune      225930
4          Diesel       Manual     Second  White    Kolkata       43404
...           ...          ...        ...    ...        ...         ...
1004995    Petrol       Manual      First  Black  Ahmedabad       68571
1004996       CNG    Automatic      First    NaN       Pune      311400
1004997    Petrol          NaN      First  Brown      Delhi       42140
1004998    Petrol       Manual      First  Brown     Mumbai      211980
1004999    Petrol       Manual      First   Blue    Kolkata      273045

         Insurance_Valid  Service_History  Accidents  Tax_Paid  \
0                      1                1          0         1
1                      0                1          0         1
2                      1                0          0         1
3                      1                1          3         1
4                      1                0          0         1
...                  ...              ...        ...       ...
1004995                1                0          0         1
1004996                1                1          0         1
1004997                0                1          0         1
1004998                0                1          0         1
1004999                1                1          0         1

         Number_of_Doors  Seats  Registration_Age         Price
0                      4      5                24  3.531896e+05
1                      4      5                13  9.596943e+05
2                      5      5                17  2.920229e+05
3                      4      5                10  2.949453e+06
4                      5      5                 3  6.365208e+05
...                  ...    ...               ...           ...
1004995                4      5                 3  1.104233e+06
1004996                4      5                20  7.122346e+05
1004997                4      4                 7  1.304198e+06
1004998                4      7                15  1.866610e+06
1004999                4      7                15  5.000000e+04

[1005000 rows x 20 columns]

In [ ]:
dframe

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,3.531896e+05
1,Hyundai,i20,2012,19.478608,1130.771005,137.021719,Petrol,NaN,First,Grey,Mumbai,211510,0,1,0,1,4,5,13,9.596943e+05
2,Mahindra,Bolero,2008,17.469920,1766.466250,142.902960,NaN,Automatic,First,Black,Kolkata,333999,1,0,0,1,5,5,17,2.920229e+05
3,BMW,X1,2015,21.295421,NaN,49.782079,NaN,Manual,First,White,Pune,225930,1,1,3,1,4,5,10,2.949453e+06
4,Honda,Civic,2022,18.326833,1239.334935,121.505993,Diesel,Manual,Second,White,Kolkata,43404,1,0,0,1,5,5,3,6.365208e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004995,Nissan,Magnite,2022,12.256422,1773.657889,117.574596,Petrol,Manual,First,Black,Ahmedabad,68571,1,0,0,1,4,5,3,1.104233e+06
1004996,Honda,Amaze,2005,NaN,1705.773023,99.643689,CNG,Automatic,First,NaN,Pune,311400,1,1,0,1,4,5,20,7.122346e+05
1004997,Skoda,Octavia,2018,21.665335,1447.159515,NaN,Petrol,NaN,First,Brown,Delhi,42140,0,1,0,1,4,4,7,1.304198e+06
1004998,BMW,X3,2010,17.852635,2179.906631,NaN,Petrol,Manual,First,Brown,Mumbai,211980,0,1,0,1,4,7,15,1.866610e+06
1004999,Ford,Endeavour,2010,20.839002,800.000000,11.857082,Petrol,Manual,First,Blue,Kolkata,273045,1,1,0,1,4,7,15,5.000000e+04

In [ ]:
import pandas as pd

df = pd.read_csv("usedcars.csv")
print(df.shape)
print(df.columns)

(1005000, 20)
Index(['Brand', 'Model', 'Year', 'Mileage_kmpl', 'Engine_CC', 'Horsepower',
       'Fuel_Type', 'Transmission', 'Owner_Type', 'Color', 'City',
       'Kms_Driven', 'Insurance_Valid', 'Service_History', 'Accidents',
       'Tax_Paid', 'Number_of_Doors', 'Seats', 'Registration_Age', 'Price'],
      dtype='object')

In [ ]:
fi=dframe['Brand']=='Toyota'
dframe.loc[fi]

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,353189.604153
5,Toyota,Camry,2007,NaN,1513.157430,100.927306,Petrol,Automatic,Second,NaN,NaN,321426,0,0,1,1,4,2,18,519526.423882
11,Toyota,Camry,2016,NaN,1553.812047,97.547550,Petrol,Automatic,Third,Black,Pune,136179,0,1,0,1,4,5,9,213122.530588
18,Toyota,Camry,2006,15.258648,1759.413790,139.156544,Petrol,Manual,First,Blue,Hyderabad,447127,1,1,0,1,4,5,19,50000.000000
25,Toyota,Yaris,2016,NaN,1694.915565,146.259864,Petrol,Manual,First,Grey,Hyderabad,206883,1,0,0,1,4,7,9,196042.939755
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004942,Toyota,Yaris,2005,NaN,1197.099021,88.327370,CNG,Manual,Fourth+,White,Pune,486560,1,1,0,1,4,5,20,50000.000000
1004960,Toyota,Corolla,2008,12.783504,988.490276,105.179968,Petrol,Manual,First,Blue,Ahmedabad,394689,1,0,1,1,4,5,17,50000.000000
1004963,Toyota,Yaris,2014,18.126993,1006.904721,74.740377,CNG,Automatic,First,Red,Mumbai,266783,1,0,0,1,4,7,11,522473.146651
1004974,Toyota,Camry,2004,21.289970,2102.058655,176.965808,NaN,Manual,First,Brown,Mumbai,364056,0,1,0,1,4,5,21,452518.773751
1004977,Toyota,Corolla,2001,20.786378,1728.841702,172.839808,Diesel,Manual,Second,Black,Hyderabad,373512,1,0,0,1,5,7,24,246427.278213

In [ ]:
fi=dframe['Brand']=='Toyota'
dframe.loc[fi].head(10)

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
0,Toyota,Camry,2001,19.615852,1396.560379,NaN,Hybrid,Automatic,First,Grey,Chennai,500928,1,1,0,1,4,5,24,3.531896e+05
5,Toyota,Camry,2007,NaN,1513.157430,100.927306,Petrol,Automatic,Second,NaN,NaN,321426,0,0,1,1,4,2,18,5.195264e+05
11,Toyota,Camry,2016,NaN,1553.812047,97.547550,Petrol,Automatic,Third,Black,Pune,136179,0,1,0,1,4,5,9,2.131225e+05
18,Toyota,Camry,2006,15.258648,1759.413790,139.156544,Petrol,Manual,First,Blue,Hyderabad,447127,1,1,0,1,4,5,19,5.000000e+04
25,Toyota,Yaris,2016,NaN,1694.915565,146.259864,Petrol,Manual,First,Grey,Hyderabad,206883,1,0,0,1,4,7,9,1.960429e+05
45,Toyota,Camry,2012,24.715593,1439.234695,145.272997,Diesel,Automatic,First,Red,NaN,260247,0,1,0,1,4,7,13,9.336990e+05
78,Toyota,Corolla,2002,19.375264,1938.788070,162.223557,Diesel,Automatic,Second,NaN,Ahmedabad,129329,1,0,0,1,4,5,23,7.744996e+05
84,Toyota,Camry,2011,18.207507,1851.570601,150.787928,Diesel,Automatic,Second,Red,Hyderabad,122066,1,1,0,1,4,5,14,1.081717e+06
91,Toyota,Camry,2019,NaN,NaN,184.158352,Petrol,Manual,First,Brown,Ahmedabad,115506,1,1,0,1,5,4,6,9.308445e+05
107,Toyota,Camry,2007,NaN,1954.181684,165.002483,Hybrid,Automatic,First,White,Hyderabad,427428,1,1,1,1,2,5,18,5.000000e+04

In [ ]:
flit=(dframe['Brand']=='Toyota')
dframe.loc[flit].sort_index(ascending=False).head(10)

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
1004977,Toyota,Corolla,2001,20.786378,1728.841702,172.839808,Diesel,Manual,Second,Black,Hyderabad,373512,1,0,0,1,5,7,24,2.464273e+05
1004974,Toyota,Camry,2004,21.289970,2102.058655,176.965808,NaN,Manual,First,Brown,Mumbai,364056,0,1,0,1,4,5,21,4.525188e+05
1004963,Toyota,Yaris,2014,18.126993,1006.904721,74.740377,CNG,Automatic,First,Red,Mumbai,266783,1,0,0,1,4,7,11,5.224731e+05
1004960,Toyota,Corolla,2008,12.783504,988.490276,105.179968,Petrol,Manual,First,Blue,Ahmedabad,394689,1,0,1,1,4,5,17,5.000000e+04
1004942,Toyota,Yaris,2005,NaN,1197.099021,88.327370,CNG,Manual,Fourth+,White,Pune,486560,1,1,0,1,4,5,20,5.000000e+04
1004918,Toyota,Camry,2018,18.237145,1681.705667,NaN,Hybrid,Manual,First,Black,Bangalore,113435,0,0,0,1,4,7,7,1.253758e+06
1004912,Toyota,Yaris,2002,20.906947,1503.314227,130.840634,Diesel,Manual,First,Brown,Kolkata,208242,1,1,1,1,4,4,23,3.980292e+05
1004910,Toyota,Camry,2008,25.708823,1585.480548,NaN,Diesel,Manual,Second,Red,Delhi,274618,1,1,0,1,4,5,17,5.679046e+05
1004887,Toyota,Camry,2004,19.149227,2180.863081,188.146689,NaN,Manual,First,Black,Delhi,284298,1,1,0,1,4,7,21,5.000000e+04
1004884,Toyota,Corolla,2005,16.667552,1255.562044,118.458319,Diesel,Manual,First,Blue,Bangalore,291000,1,0,0,1,4,2,20,5.976158e+05

In [ ]:
flit=(dframe['Brand']=='Toyota') & (dframe['City']=='Hyderabad') & (dframe['Fuel_Type']=='CNG')
dframe.loc[flit].sort_index(ascending=False).head(5)

,Brand,Model,Year,Mileage_kmpl,Engine_CC,Horsepower,Fuel_Type,Transmission,Owner_Type,Color,City,Kms_Driven,Insurance_Valid,Service_History,Accidents,Tax_Paid,Number_of_Doors,Seats,Registration_Age,Price
999279,Toyota,Yaris,2012,17.125495,1240.563335,90.673276,CNG,Manual,First,Black,Hyderabad,276419,1,0,0,1,5,4,13,3.816117e+05
998805,Toyota,Camry,2017,15.527558,1067.298489,53.323059,CNG,Automatic,First,Red,Hyderabad,94216,1,1,0,1,4,5,8,2.960714e+05
998761,Toyota,Yaris,2023,NaN,1925.353481,157.153893,CNG,Manual,First,Black,Hyderabad,42882,0,1,0,1,4,5,2,1.277681e+06
997268,Toyota,Corolla,2022,13.010858,2038.098884,160.610667,CNG,NaN,First,Blue,Hyderabad,67890,1,1,0,1,4,5,3,1.428006e+06
996993,Toyota,Yaris,2017,19.000076,1252.603430,87.769745,CNG,Manual,First,NaN,Hyderabad,71144,1,1,0,0,5,5,8,1.180768e+06